### ISSUE TITLE
Standard EMV tag key mapping

### ISSUE THREAD

**Issue by sachin-varshney** [AuthorizeNet/inperson-sdk-android#55] opened 2018-10-22 13:42 UTC
The Result object is returned to the merchant's app. The Result object contains all the values present in a regular API Result object. In addition, it has the EMV response data in a hash map. **Standard EMV tag values can be used as keys to retrieve information from the hash map**. For example, to retrieve application ID:

HashMap<String,String> map = result.getEmvTlvMap(); String applicationId= map.get("4f");

Where I can see the all map key map list.
And what is the key 9f10.
I always get the value of 9f10 same i.e. 06010A03A0A002, Can you tell me why?
Any help would be appreciated. :)

**Comment by amimishr** [comment] 2021-05-15 05:41
duplicate of #54

**Closed by amimishr** 2021-05-15 05:41 UTC
